# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Kaprao.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(829, 1039)
        MainWindow.setStyleSheet("background-color: rgb(255, 162, 138);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(0, 0, 51, 28))
        self.pushButton_5.setStyleSheet("background-color: rgb(255, 216, 183);")
        self.pushButton_5.setObjectName("pushButton_5")
        self.foodpic = QtWidgets.QGraphicsView(self.centralwidget)
        self.foodpic.setGeometry(QtCore.QRect(0, 0, 831, 441))
        self.foodpic.setStyleSheet("border-image: url(:/pic/67ba09fcb72845bc81fd413036e3f4eb.png);")
        self.foodpic.setObjectName("foodpic")
        self.ingredient = QtWidgets.QTextBrowser(self.centralwidget)
        self.ingredient.setGeometry(QtCore.QRect(30, 460, 381, 531))
        self.ingredient.setStyleSheet("background-color: rgb(255, 223, 212);\n"
"border-radius: 15px;")
        self.ingredient.setObjectName("ingredient")
        self.recipe = QtWidgets.QTextBrowser(self.centralwidget)
        self.recipe.setGeometry(QtCore.QRect(430, 460, 381, 531))
        self.recipe.setStyleSheet("background-color: rgb(255, 223, 212);\n"
"border-radius: 15px;")
        self.recipe.setObjectName("recipe")
        self.foodpic.raise_()
        self.pushButton_5.raise_()
        self.ingredient.raise_()
        self.recipe.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 829, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_5.setText(_translate("MainWindow", "Back"))
        self.ingredient.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt; font-weight:600; text-decoration: underline;\">วัตถุดิบ</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">หมูสับ 300 กรัม</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">ใบกะเพรา 50 กรัม</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">พริกแดงจินดา 1 ช้อนโต๊ะ</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">กระเทียม 1 ช้อนโต๊ะ</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">ซอสหอยนางรม 1 ช้อนโต๊ะ</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">น้ำปลา 1 ช้อนโต๊ะ </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">น้ำตาลทราย 1 ช้อนชา</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">น้ำมัน (สำหรับผัดกะเพรา) 1 ช้อนโต๊ะ</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">ไข่ไก่ 1 ฟอง</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">น้ำมัน (สำหรับทอดไข่ดาว) ½ ถ้วยตวง</span></p></body></html>"))
        self.recipe.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt; font-weight:600; text-decoration: underline;\">วิธีทำ</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">STEP 1 : ทอดไข่ดาวกรอบ ๆ</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">1.ตั้งกระใส่น้ำมันรอให้ร้อนจัด ค่อยตอกไข่ไก่ลงไปทอดจนไข่ดาวกรอบ 2.ตักขึ้นพักไว้ให้สะเด็ดน้ำมัน </span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:10pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">STEP 2 : ทำผัดกะเพราหมูสับ</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">1.ตั้งกระทะใส่น้ำมันให้พอร้อน แล้วใส่กระเทียม และพริกแดงจินดาลงไปผัดจนส่งกลิ่นหอม จากนั้นใส่หมูสับลงไปผัด</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">2.เมื่อหมูเริ่มสุกให้ปรุงรสด้วย ซอสหอยนางรม น้ำปลา และน้ำตาลทราย 3.ผัดจนทุกอย่างเข้ากันดี จากนั้นใส่ใบกะเพราลงไปผัดให้สลดลงเล็กน้อย</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:10pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">STEP 3 : จัดเสิร์ฟผัดกะเพราหมูสับไข่ดาว</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">ตักข้าวสวยร้อน ๆ ใส่จานราดด้วยหมูสับผัดกะเพราหมูสับ โปะด้วยไข่ดาวกรอบ ๆ เสิร์ฟพร้อมน้ำปลาพริก</span></p></body></html>"))
import foodpic_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
