# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Maindish.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(607, 846)
        MainWindow.setStyleSheet("background-color: rgb(255, 162, 138);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.menu1 = QtWidgets.QPushButton(self.centralwidget)
        self.menu1.setGeometry(QtCore.QRect(150, 120, 301, 91))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.menu1.setFont(font)
        self.menu1.setStyleSheet("background-color: rgb(158, 97, 98);\n"
"border-radius: 15px;")
        self.menu1.setObjectName("menu1")
        self.menu2 = QtWidgets.QPushButton(self.centralwidget)
        self.menu2.setGeometry(QtCore.QRect(150, 280, 301, 91))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.menu2.setFont(font)
        self.menu2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 192, 66);\n"
"border-radius: 15px;")
        self.menu2.setObjectName("menu2")
        self.menu3 = QtWidgets.QPushButton(self.centralwidget)
        self.menu3.setGeometry(QtCore.QRect(150, 440, 301, 91))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.menu3.setFont(font)
        self.menu3.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"background-color: rgb(229, 113, 115);\n"
"border-radius: 15px;")
        self.menu3.setObjectName("menu3")
        self.menu4 = QtWidgets.QPushButton(self.centralwidget)
        self.menu4.setGeometry(QtCore.QRect(150, 590, 301, 91))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.menu4.setFont(font)
        self.menu4.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 242, 192);\n"
"border-radius: 15px;")
        self.menu4.setObjectName("menu4")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(220, 10, 161, 71))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.back = QtWidgets.QPushButton(self.centralwidget)
        self.back.setGeometry(QtCore.QRect(0, 0, 41, 28))
        self.back.setStyleSheet("background-color: rgb(255, 216, 183);")
        self.back.setObjectName("back")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 607, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menu1.setText(_translate("MainWindow", "กะเพราหมูสับ"))
        self.menu2.setText(_translate("MainWindow", "ข้าวผัด"))
        self.menu3.setText(_translate("MainWindow", "หมูทอด"))
        self.menu4.setText(_translate("MainWindow", "แกงจืด"))
        self.label.setText(_translate("MainWindow", "เลือกเมนูเลย!"))
        self.back.setText(_translate("MainWindow", "Back"))
import foodpic_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
